name: Deploy to Production

on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Pull Docker image
        run: |
          IMAGE_TAG=${{ inputs.image-tag }}
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY_OWNER}/flask-app:${IMAGE_TAG}"
          docker pull $IMAGE_NAME

      - name: Update Deployment.yaml in flask-infra
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          IMAGE_TAG=${{ inputs.image-tag }}
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY_OWNER}/flask-app:${IMAGE_TAG}"

          sudo apt-get update && sudo apt-get install -y git
          git clone https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY_OWNER}/flask-infra.git
          cd flask-infra

          sed -i "s|image: ghcr.io/.*/flask-app:.*|image: $IMAGE_NAME|g" Deployment.yaml

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Deployment.yaml
          git commit -m "Update Deployment image to $IMAGE_TAG" || echo "No changes to commit"
          git push origin main
