name: Docker Build & Scan

on:
  workflow_run:
    workflows: ["Unit & Integration Tests"]
    types:
      - completed

jobs:
  docker_build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.build.outputs.image-tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        id: build
        run: |
          SANITIZED_REF_NAME=$(echo "${GITHUB_REF_NAME}" | tr '/' '-')
          SHORT_SHA=${GITHUB_SHA::8}
          IMAGE_TAG="${SANITIZED_REF_NAME}-${SHORT_SHA}"
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY_OWNER}/flask-app:${IMAGE_TAG}"

          echo "Building Docker image ${IMAGE_NAME}..."
          docker build -t flask-app:latest .

          docker tag flask-app:latest $IMAGE_NAME
          docker push $IMAGE_NAME

          echo "image-tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Docker image security scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: flask-app:latest
          format: table

      - name: Print workflow name
        run:
          echo "Workflow name: ${{ github.workflow }}"

