name: Orchestrator

on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint-type-check.yml

  security:
    needs: lint
    uses: ./.github/workflows/security-checks.yml

  tests:
    needs: security
    uses: ./.github/workflows/tests.yml

  docker:
    needs: tests
    uses: ./.github/workflows/docker-build-scan.yml

  deploy:
    needs: docker
    uses: ./.github/workflows/deploy.yml
